// Generated by gencpp from file control_pkg/Diff_drive.msg
// DO NOT EDIT!


#ifndef CONTROL_PKG_MESSAGE_DIFF_DRIVE_H
#define CONTROL_PKG_MESSAGE_DIFF_DRIVE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace control_pkg
{
template <class ContainerAllocator>
struct Diff_drive_
{
  typedef Diff_drive_<ContainerAllocator> Type;

  Diff_drive_()
    : v(0.0)
    , w(0.0)  {
    }
  Diff_drive_(const ContainerAllocator& _alloc)
    : v(0.0)
    , w(0.0)  {
  (void)_alloc;
    }



   typedef float _v_type;
  _v_type v;

   typedef float _w_type;
  _w_type w;





  typedef boost::shared_ptr< ::control_pkg::Diff_drive_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control_pkg::Diff_drive_<ContainerAllocator> const> ConstPtr;

}; // struct Diff_drive_

typedef ::control_pkg::Diff_drive_<std::allocator<void> > Diff_drive;

typedef boost::shared_ptr< ::control_pkg::Diff_drive > Diff_drivePtr;
typedef boost::shared_ptr< ::control_pkg::Diff_drive const> Diff_driveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::control_pkg::Diff_drive_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::control_pkg::Diff_drive_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace control_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'control_pkg': ['/home/pi/catkin_gp/src/control_pkg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::control_pkg::Diff_drive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_pkg::Diff_drive_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_pkg::Diff_drive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_pkg::Diff_drive_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_pkg::Diff_drive_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_pkg::Diff_drive_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::control_pkg::Diff_drive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b52b8b58fa2fef1c7db8f924121a1fa";
  }

  static const char* value(const ::control_pkg::Diff_drive_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b52b8b58fa2fef1ULL;
  static const uint64_t static_value2 = 0xc7db8f924121a1faULL;
};

template<class ContainerAllocator>
struct DataType< ::control_pkg::Diff_drive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "control_pkg/Diff_drive";
  }

  static const char* value(const ::control_pkg::Diff_drive_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::control_pkg::Diff_drive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 v\n\
float32 w\n\
";
  }

  static const char* value(const ::control_pkg::Diff_drive_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::control_pkg::Diff_drive_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.v);
      stream.next(m.w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Diff_drive_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control_pkg::Diff_drive_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::control_pkg::Diff_drive_<ContainerAllocator>& v)
  {
    s << indent << "v: ";
    Printer<float>::stream(s, indent + "  ", v.v);
    s << indent << "w: ";
    Printer<float>::stream(s, indent + "  ", v.w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_PKG_MESSAGE_DIFF_DRIVE_H
