// Generated by gencpp from file control_pkg/Diff_drive.msg
// DO NOT EDIT!


#ifndef CONTROL_PKG_MESSAGE_DIFF_DRIVE_H
#define CONTROL_PKG_MESSAGE_DIFF_DRIVE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace control_pkg
{
template <class ContainerAllocator>
struct Diff_drive_
{
  typedef Diff_drive_<ContainerAllocator> Type;

  Diff_drive_()
    : header()
    , v(0.0)
    , w(0.0)  {
    }
  Diff_drive_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , v(0.0)
    , w(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _v_type;
  _v_type v;

   typedef float _w_type;
  _w_type w;





  typedef boost::shared_ptr< ::control_pkg::Diff_drive_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control_pkg::Diff_drive_<ContainerAllocator> const> ConstPtr;

}; // struct Diff_drive_

typedef ::control_pkg::Diff_drive_<std::allocator<void> > Diff_drive;

typedef boost::shared_ptr< ::control_pkg::Diff_drive > Diff_drivePtr;
typedef boost::shared_ptr< ::control_pkg::Diff_drive const> Diff_driveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::control_pkg::Diff_drive_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::control_pkg::Diff_drive_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace control_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'control_pkg': ['/home/pi/catkin_gp/src/control_pkg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::control_pkg::Diff_drive_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_pkg::Diff_drive_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_pkg::Diff_drive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_pkg::Diff_drive_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_pkg::Diff_drive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_pkg::Diff_drive_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::control_pkg::Diff_drive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c9739f01512ce85d8ac1ccdd6bde650b";
  }

  static const char* value(const ::control_pkg::Diff_drive_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc9739f01512ce85dULL;
  static const uint64_t static_value2 = 0x8ac1ccdd6bde650bULL;
};

template<class ContainerAllocator>
struct DataType< ::control_pkg::Diff_drive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "control_pkg/Diff_drive";
  }

  static const char* value(const ::control_pkg::Diff_drive_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::control_pkg::Diff_drive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
float32 v\n\
float32 w\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::control_pkg::Diff_drive_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::control_pkg::Diff_drive_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.v);
      stream.next(m.w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Diff_drive_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control_pkg::Diff_drive_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::control_pkg::Diff_drive_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "v: ";
    Printer<float>::stream(s, indent + "  ", v.v);
    s << indent << "w: ";
    Printer<float>::stream(s, indent + "  ", v.w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_PKG_MESSAGE_DIFF_DRIVE_H
